function expandsubplot
set(gca, 'ButtonDownFcn',@(ax,~) ...
    set(copyobj(ax,uipanel('Position',[0,0,1,1])),...
    'Units','normal', 'OuterPosition',[0,0,1,1], ...
    'ButtonDownFcn',@(co,~)delete(get(co,'parent'))));
end